In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("BlackFriday.csv")
del df['Product_Category_2']
del df['Product_Category_3']

In [4]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  Purchase  
0                          2               0                   3      8370  
1                          2               0                   1     15200  
2                          2               0                  12      1422  
3                          2               0                  12      1057  
4                         4+               0                   8      7969

In [5]:
## Unique no. of User ID
df['User_ID'].nunique()

5891

In [6]:
## Unique no. of Product ID 
df['Product_ID'].nunique()

3623

In [7]:
## Unique Gender
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [8]:
## Unique Age
df['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [9]:
## Unique Occupations
df['Occupation'].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

In [10]:
## Unique cities
df['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [11]:
## Unique year of experience of living
df['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [12]:
## Maarital Status
df['Marital_Status'].unique()

array([0, 1], dtype=int64)

In [13]:
## Unique Products in Product_Category_1
df['Product_Category_1'].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9], dtype=int64)

In [14]:
## total Purchases in BFS
df['Purchase'].sum()

5017668378

In [15]:
## Average Purchase By a user 
df['Purchase'].sum()/len(df['Purchase'])

9333.859852635065

In [16]:
## AUtomate in One for loop
for column in df.columns:
    print(column, df[column].nunique())

User_ID 5891
Product_ID 3623
Gender 2
Age 7
Occupation 21
City_Category 3
Stay_In_Current_City_Years 5
Marital_Status 2
Product_Category_1 18
Purchase 17959
